---
- hosts: master
  become_method: sudo
  gather_facts: False

  pre_tasks:
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      become: true
    - setup:

  tasks:
  - name: Installing rkt
    become: true
    apt:
        deb: https://github.com/rkt/rkt/releases/download/v1.27.0/rkt_1.27.0-1_amd64.deb
        update_cache: yes
  - name: Running rkt metadata services
    become: true
    raw: systemd-run rkt metadata-service
  - name: Installing kubernetes binaries
    become: true
    unarchive:
      src: tmp/kubernetes/server/kubernetes-server-linux-amd64.tar.gz
      dest: /
  - name: Settings folder rights
    become: true
    file:
      path: /kubernetes
      recurse: true
      state: directory
      mode: 0755
  - name: add /kubernetes/server/bin to path
    become: true
    lineinfile:
      dest: /etc/environment
      state: present
      backrefs: yes
      regexp: 'PATH=(["]*)((?!.*?/kubernetes/server/bin).*?)(["]*)$'
      line: 'PATH=\1\2:/kubernetes/server/bin\3'
