---
- hosts: node
  become_method: sudo
  tasks:
  - name: Installing rkt
    become: true
    apt:
        deb: https://github.com/rkt/rkt/releases/download/v1.27.0/rkt_1.27.0-1_amd64.deb
        update_cache: yes
  - name: Installing systemd
    become: true
    apt:
        deb: systemd
  - name: Running rkt metadata services
    become: true
    service:
      enabled: yes
      name: rkt
      state: started
      arguments: metadata-service
  - name: Installing kubernetes binaries
    become: true
    unarchive:
      src: tmp/kubernetes/server/kubernetes-server-linux-amd64.tar.gz
      dest: /
  - name: Settings folder rights
    become: true
    file:
      path: /kubernetes
      recurse: true
      state: directory
      mode: 0755
  - name: add /kubernetes/server/bin to path
    become: true
    lineinfile:
      dest: /etc/environment
      state: present
      backrefs: yes
      regexp: 'PATH=(["]*)((?!.*?/kubernetes/server/bin).*?)(["]*)$'
      line: 'PATH=\1\2:/kubernetes/server/bin\3'

      
