---
- name: Creating kube-apiserver file
  become: true
  template:
    src: roles/kubernetes_master/template/kube-apiserver.service
    dest: /etc/systemd/system/kube-apiserver.service

- name: Launching kube-apiserver
  become: true
  systemd:
    name: kube-apiserver
    state: started

- name: Creating kube-controller-manager file
  become: true
  template:
    src: roles/kubernetes_master/template/kube-controller-manager.service
    dest: /etc/systemd/system/kube-controller-manager.service

- name: Launching kube-controller-manager
  become: true
  systemd:
    name: kube-controller-manager
    state: started

- name: Creating kube-scheduler file
  become: true
  template:
    src: roles/kubernetes_master/template/kube-scheduler.service
    dest: /etc/systemd/system/kube-scheduler.service

- name: Launching kube-scheduler
  become: true
  systemd:
    name: kube-scheduler
    state: started
