---
- name: Creating cluster info
  raw: "/kubernetes/server/bin/kubectl config set-cluster {{ master_name }} --server=http://{{ master_ip }}:{{ master_port }}"

- name: Creating context
  raw: "/kubernetes/server/bin/kubectl config set-context {{ master_name }} --cluster={{ master_name }}"

- name: Setting context
  raw: "/kubernetes/server/bin/kubectl config use-context {{ master_name }}"